package dx11

type IDXGIAdapter uintptr

type D3D_DRIVER_TYPE int

const (
	D3D_DRIVER_TYPE_UNKNOWN D3D_DRIVER_TYPE = iota
	D3D_DRIVER_TYPE_HARDWARE
	D3D_DRIVER_TYPE_REFERENCE
	D3D_DRIVER_TYPE_NULLD3D11_CREATE_DEVICE_SINGLETHREADED
	D3D_DRIVER_TYPE_SOFTWARE
	D3D_DRIVER_TYPE_WARP
)

type D3D_FEATURE_LEVEL int

const (
	D3D_FEATURE_LEVEL_1_0_CORE D3D_FEATURE_LEVEL = iota
	D3D_FEATURE_LEVEL_9_1
	D3D_FEATURE_LEVEL_9_2
	D3D_FEATURE_LEVEL_9_3
	D3D_FEATURE_LEVEL_10_0
	D3D_FEATURE_LEVEL_10_1
	D3D_FEATURE_LEVEL_11_0
	D3D_FEATURE_LEVEL_11_1
	D3D_FEATURE_LEVEL_12_0
	D3D_FEATURE_LEVEL_12_1
	D3D_FEATURE_LEVEL_12_2
)
